# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('CARD', 'Visa/Mastercard'),
                    ('KHALTI', 'Khalti'),
                    ('ESEWA', 'eSewa'),
                ],
                default='CARD',
                max_length=50,
            ),
        ),
    ]
